<html>
<table>
	<thead>
		<th>ID</th>
		<th>CustomerName</th>
		<th>CustomerAddress</th>
		<th>City</th>
		<th>State</th>
		<th>Zone</th>
		<th>Region</th>
		<th>MobileNo</th>
		<th>TelephoneNo</th>
		<th>EmailId</th>
		<th>FBAID</th>	
		<th>PospStatus</th>
		<th>PremiumAmount</th>
		<th>ERPID</th>
		<th>QTNo</th>
		<th>VehicleNo</th>
		<th>DateofExpiry</th>
		<th>BreakIn</th>
		<th>Insurermotor</th>
		<th>PaymentMode</th>
		<th>UTRNo</th>
		<th>Bank</th>
		<th>ExecutiveName</th>
		<th>ExecutiveName1</th>
		<th>ProductExecutive</th>
		<th>ProductManager</th>
		<th>RCCopy</th>
		<th>Fitness</th>
		<th>PUC</th>
		<th>BreakinReport</th>
		<th>ChequeCopy</th>
		<th>Other</th>
		<th>createddate</th>
	</thead>
	<tbody>
		@foreach($offlinecsdata as $val)   
		<tr>
		<td>{{$val->ID}}</td>
		<td>{{$val->product_name}}</td>
		<td>{{$val->CustomerName}}</td>
		<td>{{$val->CustomerAddress}}</td>
		<td>{{$val->cityname}}</td>
		<td>{{$val->state_name}}</td>
		<td>{{$val->Zone}}</td>
		<td>{{$val->Region}}</td>
		<td>{{$val->MobileNo}}</td>
		<td>{{$val->TelephoneNo}}</td>
		<td>{{$val->EmailId}}</td>
		<td>{{$val->product_name}}</td>	
		<td>{{$val->PospStatus}}</td>
		<td>{{$val->PremiumAmount}}</td>
		<td>{{$val->ERPID}}</td>
		<td>{{$val->QTNo}}</td>
		<td>{{$val->VehicleNo}}</td>
		<td>{{$val->DateofExpiry}}</td>
		<td>{{$val->BreakIn}}</td>
		<td>{{$val->motorInsurer}}</td>
		<td>{{$val->PaymentMode}}</td>
		<td>{{$val->UTRNo}}</td>
		<td>{{$val->Bank}}</td>
		<td>{{$val->ExecutiveName}}</td>
		<td>{{$val->ExecutiveName1}}</td>
		<td>{{$val->ProductExecutive}}</td>
		<td>{{$val->ProductManager}}</td>
		<td>{{$val->RCCopy}}</td>
		<td>{{$val->Fitness}}</td>
		<td>{{$val->PUC}}</td>
		<td>{{$val->BreakinReport}}</td>
		<td>{{$val->ChequeCopy}}</td>
		<td>{{$val->Other}}</td>
		<td>{{$val->createddate}}</td>
		</tr>
       @endforeach
	</tbody>	
</table>
</html>